# Site settings
title: Dynaguy
description: My personal page :)
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Dynaguy
user_description: Self taught coder. Android entusiast. Cyber-Sec Entusiast. Basically I love everything related to computers and phones.
user_title: Web Developer, Publisher
email: thedynaguy@gmail.com
github_username:  thedynaguy


# Google-analytics
#google-analytics:
#  id: ""

exclude: ['package.json', 'src' , 'node_modules']
